### ISSUE TITLE
lightfall is incompatible with version 1.18.2

### ISSUE THREAD

**Issue by Fuwayuka** [ArclightPowered/lightfall#24]

**Comment by Fuwayuka** [comment]
![2022-03-19_11 03 47](https://user-images.githubusercontent.com/99341213/159102672-fdf27b98-0fd8-431e-aef9-55480be8b0c1.png)

When I enter the mod server of the latest Arclight version 1.18.2, I get an error message "unexpected packet received during server login process!

**Comment by VeroFess** [comment]
This is a self-compiled lightfall server with 1.18.2 support, and since I'm not proficient with git patch, there is no way to submit a pr. It works fine on my server.

[lightfall_with_module.zip](https://github.com/ArclightPowered/lightfall/files/8527345/lightfall_with_module.zip)

![image](https://user-images.githubusercontent.com/21025099/164374278-a7e82cd5-818a-4743-8584-0ea1e9c54e39.png)
